<a href="https://colab.research.google.com/github/DITHAAAA/Stupen_Batch5/blob/main/Sesi_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [1]:
import numpy as np

In [2]:
[1, 2, 3, 4]

[1, 2, 3, 4]

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [5]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
a.ndim

2

In [7]:
a.shape

(3, 4)

In [8]:
b = np.array(
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]],
        [[9, 10], [11, 12]]
    ]
)

In [9]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [10]:
b.ndim

3

In [11]:
b.shape

(3, 2, 2)

# **Array**

np.array()

np.zeros()

np.ones()

np.empty()

np.arange()

In [12]:
np.array([1, 2, 3])

array([1, 2, 3])

In [13]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [15]:
np.empty((2, 2))

array([[1., 1.],
       [1., 1.]])

In [16]:
range(5)

range(0, 5)

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

# **Add, Remove, Sort**

np.append()

np.delete()

np.sort()

In [18]:
arr = np.arange(8)
mylist = list(range(8))

In [19]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
mylist.append([1, 2])

In [21]:
mylist

[0, 1, 2, 3, 4, 5, 6, 7, [1, 2]]

In [22]:
np.append(arr, [[1, 2]])

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [23]:
arr = np.append(arr, [1, 2])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [24]:
np.delete(arr, 1)

array([0, 2, 3, 4, 5, 6, 7, 1, 2])

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [26]:
np.sort(arr)

array([0, 1, 1, 2, 2, 3, 4, 5, 6, 7])

In [27]:
print("dim", arr.ndim)
print("size", arr.size)
print("shape", arr.shape)

dim 1
size 10
shape (10,)


In [28]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
print("dim", a.ndim)
print("size", a.size)
print("shape", a.shape)

dim 2
size 12
shape (3, 4)


In [30]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [31]:
print("dim", b.ndim)
print("size", b.size)
print("shape", b.shape)

dim 3
size 12
shape (3, 2, 2)


In [32]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [33]:
print("dim", array_example.ndim)
print("size", array_example.size)
print("shape", array_example.shape)

dim 3
size 24
shape (3, 2, 4)


# **Reshape**

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [35]:
arr.shape

(10,)

In [36]:
arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 1, 2]])

In [37]:
arr.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [1, 2]])

In [38]:
arr3 = arr.reshape(5, 2)

In [39]:
arr3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [1, 2]])

# **Convert 1D to 2D**

np.newaxis

np.expand_dims

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [41]:
arr.shape

(10,)

In [42]:
arr4 = arr[np.newaxis, :]

In [43]:
arr4

array([[0, 1, 2, 3, 4, 5, 6, 7, 1, 2]])

In [44]:
arr4.ndim

2

In [45]:
arr4.shape

(1, 10)

In [46]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
a.shape

(3, 4)

In [48]:
np.expand_dims(a, axis=0).shape

(1, 3, 4)

In [49]:
a[np.newaxis, :].shape

(1, 3, 4)

# **Indexing and Slicing**

      arr[start:stop:step]

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [51]:
arr[8]

1

In [52]:
arr[4:]

array([4, 5, 6, 7, 1, 2])

In [53]:
arr > 2

array([False, False, False,  True,  True,  True,  True,  True, False,
       False])

In [54]:
arr[arr > 2]

array([3, 4, 5, 6, 7])

In [55]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
a < 8

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [57]:
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [58]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [59]:
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [60]:
a % 3 == 0

array([[False, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True]])

In [61]:
(a % 2 == 0) & (a % 3 == 0)

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [62]:
a[(a % 2 == 0) & (a % 3 == 0)]

array([ 6, 12])

# **Creating from Existing Data**

np.vstack()

np.hstack()

np.vsplit()

np.hsplit()

.view()
.copy()

In [63]:
arr1 = arr[3:8]

In [64]:
arr1

array([3, 4, 5, 6, 7])

In [65]:
a_1 = np.array([[1, 1], [2, 2]])
print(a_1.shape)
a_1

(2, 2)


array([[1, 1],
       [2, 2]])

In [66]:
a_2 = np.array([[3, 3], [4, 4]])
print(a_2.shape)
a_2

(2, 2)


array([[3, 3],
       [4, 4]])

In [67]:
np.vstack([a_1, a_2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [68]:
np.hstack([a_1, a_2])

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [69]:
arrsplit = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [70]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [71]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
np.hsplit(a, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [73]:
np.vsplit(a, 3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [74]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
b = a

In [76]:
print(id(a))
print(id(b))
print(id(a) == id(b))

137383686191504
137383686191504
True


In [77]:
b = a.view()

In [78]:
print(id(a))
print(id(b))
print(id(a) == id(b))

137383686191504
137383687049296
False


In [79]:
c = a.copy()

In [80]:
print(id(a))
print(id(c))
print(id(a) == id(c))

137383686191504
137383802555056
False


# **Basic Array Operations**

+

(-)

/

*

In [81]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [82]:
arr + 1

array([1, 2, 3, 4, 5, 6, 7, 8, 2, 3])

In [83]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35,  5, 10])

In [84]:
[1, 2, 3] * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [85]:
[1, 2, 3] + [5]

[1, 2, 3, 5]

In [86]:
arr + np.array([5])

array([ 5,  6,  7,  8,  9, 10, 11, 12,  6,  7])

In [87]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 0.5, 1. ])

In [88]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [89]:
data = np.array([1, 2])
data

array([1, 2])

In [90]:
ones = np.ones(2)
ones

array([1., 1.])

In [91]:
data + ones

array([2., 3.])

In [92]:
data * ones

array([1., 2.])

In [93]:
data * 2

array([2, 4])

In [94]:
data + 2

array([3, 4])

# **Array Operations**

data.max()

data.min()

data.sum()

data.mean()

data.std()

data.var()

In [95]:
%%timeit
sum([1, 2, 3, 4])

354 ns ± 51.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [96]:
%%timeit
np.arange(1, 5).sum()

3.76 µs ± 297 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [97]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [98]:
print(arr.sum())
print(arr.max())
print(arr.min())

31
7
0


# **Matrices**

In [99]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [100]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [101]:
np.random.random((3, 2))

array([[0.20400914, 0.55257855],
       [0.87243372, 0.425312  ],
       [0.39850534, 0.00651982]])

# **Matrix Arithmetic**

In [102]:
data = np.arange(1, 5).reshape(2, 2)
ones = np.ones((2, 2))
ones_row = np.ones((1, 2))

print(data)
print(ones)
print(ones_row)

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]]


In [103]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [104]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


# **Dot Product**

In [105]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [106]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [107]:
np.dot(a_2, a_1)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

# **Matrix Indexing**

In [108]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
a[0][0]

1

In [110]:
a[1][2]

7

In [111]:
a[2][-1]

12

In [112]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


# **Matrix Aggregation**

In [113]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [114]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [115]:
data.shape

(3, 2)

In [116]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [117]:
print(data.sum(axis=0))
print(data.sum(axis=1))

[ 9 12]
[ 3  7 11]


# **Transposing**

In [118]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [120]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [121]:
data.shape

(3, 2)

In [122]:
data.reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [123]:
data.reshape((6, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [124]:
data.reshape((1, 6))

array([[1, 2, 3, 4, 5, 6]])

In [125]:
np.arange(15).reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [126]:
np.linspace(0, 50, num=20).reshape((5, 4))

array([[ 0.        ,  2.63157895,  5.26315789,  7.89473684],
       [10.52631579, 13.15789474, 15.78947368, 18.42105263],
       [21.05263158, 23.68421053, 26.31578947, 28.94736842],
       [31.57894737, 34.21052632, 36.84210526, 39.47368421],
       [42.10526316, 44.73684211, 47.36842105, 50.        ]])

# **N Dimensional Array**

In [127]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [128]:
ndarr.shape

(2, 2, 2)

In [129]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [130]:
randomarr = np.random.random((4, 3, 2))
randomarr

array([[[0.28174038, 0.07715723],
        [0.08468342, 0.62193491],
        [0.11058185, 0.72264969]],

       [[0.28077152, 0.83943465],
        [0.34334782, 0.51135497],
        [0.65061388, 0.98968227]],

       [[0.40045703, 0.19792957],
        [0.76185647, 0.40587131],
        [0.61612346, 0.63887382]],

       [[0.53424804, 0.8773837 ],
        [0.9133532 , 0.66795975],
        [0.4267203 , 0.03821557]]])

In [131]:
randomarr.flatten()

array([0.28174038, 0.07715723, 0.08468342, 0.62193491, 0.11058185,
       0.72264969, 0.28077152, 0.83943465, 0.34334782, 0.51135497,
       0.65061388, 0.98968227, 0.40045703, 0.19792957, 0.76185647,
       0.40587131, 0.61612346, 0.63887382, 0.53424804, 0.8773837 ,
       0.9133532 , 0.66795975, 0.4267203 , 0.03821557])

In [132]:
randomarr.reshape(-1)

array([0.28174038, 0.07715723, 0.08468342, 0.62193491, 0.11058185,
       0.72264969, 0.28077152, 0.83943465, 0.34334782, 0.51135497,
       0.65061388, 0.98968227, 0.40045703, 0.19792957, 0.76185647,
       0.40587131, 0.61612346, 0.63887382, 0.53424804, 0.8773837 ,
       0.9133532 , 0.66795975, 0.4267203 , 0.03821557])

In [133]:
randomarr.reshape(24,)

array([0.28174038, 0.07715723, 0.08468342, 0.62193491, 0.11058185,
       0.72264969, 0.28077152, 0.83943465, 0.34334782, 0.51135497,
       0.65061388, 0.98968227, 0.40045703, 0.19792957, 0.76185647,
       0.40587131, 0.61612346, 0.63887382, 0.53424804, 0.8773837 ,
       0.9133532 , 0.66795975, 0.4267203 , 0.03821557])

# **Math Formulas**

In [134]:
# error = (1/n) * np.sum(np.square(observed - prediction))